#ifndef ETUDE_DE_MARCHE_H
#define ETUDE_DE_MARCHE_H

#define ETUDE_PRIX 1000
#define ETUDE_PUBLICITE 1000
#define ETUDE_FORCE_VENTE 1000
#define ETUDE_PARTS_MARCHE 1000
#define ETUDE_DELAI_PAIEMENT 1000
#define ETUDE_SENSIBILITE_CLIENTS 3000
#define ETUDE_VOLUME_PREVISIONNEL 3000

#endif