#ifndef ETUDE_DE_MARCHE_H
#define ETUDE_DE_MARCHE_H

#define ETUDE_PRIX 1_000
#define ETUDE_PUBLICITE 1_000
#define ETUDE_FORCE_VENTE 1_000
#define ETUDE_PARTS_MARCHE 1_000
#define ETUDE_DELAI_PAIEMENT 1_000
#define ETUDE_SENSIBILITE_CLIENTS 3_000
#define ETUDE_VOLUME_PREVISIONNEL 3_000

#endif