#ifndef OUTILS_DE_PRODUCTION
#define OUTILS_DE_PRODUCTION

#define COUT_FIXE_PAR_MACHINE 10000
#define COUT_VARIABLE_PAR_HEURE 9.0f
#define NB_HEURE_PAR_MACHINE_PAR_MOIS 1000
#define PRIX_ACHAT_MACHINE 75000
#define PRIX_VENTE_MACHINE 60000
#define COUT_FIXE_STRUCTURE 15000

#endif